"""
State schema for LangGraph coaching workflow
This defines the "memory" that flows through all nodes
"""

from typing import TypedDict, Dict, List, Optional

class CoachingState(TypedDict):
    """
    State that flows through the entire LangGraph workflow
    Each node can read and modify this state
    """
    
    # INPUT: From IntegrationLayer
    coaching_event: Dict
    # Example structure:
    # {
    #     "event_id": "session_123_event_5",
    #     "timestamp": 15.47,
    #     "exercise": {"name": "heel lift", "confidence": 0.66},
    #     "mistake": {
    #         "type": "not moving - up",
    #         "confidence": 0.45,
    #         "duration_seconds": 4.2,
    #         "persistence_rate": 0.45
    #     },
    #     "metrics": {...},
    #     "severity": "high",
    #     "tier": "tier_2",
    #     "cache_key": "heel_lift_not_moving_up"
    # }
    
    # SESSION CONTEXT: Loaded by enrich_context node
    session_id: str
    patient_profile: Optional[Dict]  # Loaded from database
    coaching_history: List[Dict]     # History from current session
    
    # ROUTING: Set by IntegrationLayer, used by graph
    tier: str  # "tier_1", "tier_2", or "tier_3"
    cache_key: Optional[str]  # For Tier 1 cache lookup
    routing_reason: str  # Why this tier was chosen
    
    # RAG CONTEXT: Retrieved by Tier 2/3 nodes
    retrieved_docs: Optional[List[str]]  # Documents from RAG
    
    # AGENT OUTPUTS
    movement_analysis: Optional[str]  # From Movement Analysis Agent
    coaching_response: str  # Generated coaching text
    feedback_audio: str  # Final polished feedback for patient
    
    # DELIVERY METADATA
    delivery_timing: str  # "immediate", "rep_end", "rest_period"
    tier_used: str  # Which tier actually processed this
    
    # PERFORMANCE METRICS
    latency_ms: Optional[float]  # End-to-end latency
    
    # PROGRESS TRACKING (optional)
    session_summary: Optional[Dict]  # Generated by Progress Agent